---
- name: Copy file to remote server
  hosts: all
  become: true  # Optional, if you need to escalate privileges to copy to certain directories
  vars:
    ansible_user: vagrant
    ansible_ssh_private_key_file: /var/lib/jenkins/.ssh/vagrant_key

tasks:
    - name: Create file (if it doesn't exist)
      command: touch /tmp/file.txt  # Creates an empty file
    - name: Copy file
      copy:
        src: /tmp/file.txt  # Source is now the newly created file
        dest: /tmp/file.txt  # Destination on the remote server
