---
- name: Copy file to remote server
  hosts: 192.168.33.11
  become: true  # Optional, if you need to escalate privileges to copy to certain directories

  tasks:
    - name: Copy file
      copy:
        src: /tmp/file.txt  # Path to the local file you want to copy
        dest: /tmp/file.txt  # Path to the destination on the remote server
